"""Reversible statusline capture wrapper (T0 §4B, Rulebook rule 2, Guardrail 1).

Install repoints `settings.json` -> `statusLine.command` at a wrapper that captures
`.rate_limits` to ratelimits.json and then runs the *original* statusline with the same
stdin, emitting its stdout byte-for-byte unchanged. Before repointing, install **proves**
the wrapper's output is byte-identical to the original; if it isn't, it aborts without
touching settings.json.

Restore reverts **both** files to their originals and proves it by sha256:
  - settings.json  <- the exact pre-install bytes (so the statusLine block is restored)
  - statusline-command.sh  is never modified, so it already matches its .orig

Nothing here ever reads credentials or makes a network call.
"""

from __future__ import annotations

import hashlib
import json
import shlex
import shutil
import subprocess
from pathlib import Path

from .paths import (
    RATELIMITS_JSON,
    SCRIPT_ORIG,
    SETTINGS_JSON,
    SETTINGS_ORIG,
    SETTINGS_PREINSTALL,
    STATUSLINE_SCRIPT,
    WRAPPER_SCRIPT,
    ensure_dirs,
)

# Synthetic payload used only to prove byte-identical output. cwd=/tmp keeps the
# original script's `git -C` call deterministic (no repo there).
_PROOF_PAYLOAD = json.dumps(
    {
        "model": {"display_name": "Opus 4.8"},
        "context_window": {"used_percentage": 42},
        "output_style": {"name": "max"},
        "workspace": {"current_dir": "/tmp"},
        "cwd": "/tmp",
        "rate_limits": {
            "five_hour": {"used_percentage": 1, "resets_at": 9999999999},
            "seven_day": {"used_percentage": 1, "resets_at": 9999999999},
        },
    }
).encode()


def _sha256(path: Path) -> str | None:
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return None


def _read_settings() -> dict:
    try:
        data = json.loads(SETTINGS_JSON.read_text("utf-8"))
        return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError, ValueError):
        return {}


def _current_command(settings: dict) -> str:
    sl = settings.get("statusLine")
    if isinstance(sl, dict):
        cmd = sl.get("command")
        if isinstance(cmd, str):
            return cmd
    return ""


def _is_wrapped(command: str) -> bool:
    return "cc-usage" in command or "statusline-wrapper" in command


def ensure_backups() -> None:
    """Guarantee the canonical .orig backups exist (created in Task 1; recreate if absent)."""
    ensure_dirs()
    if not SETTINGS_ORIG.exists() and SETTINGS_JSON.exists():
        shutil.copy2(SETTINGS_JSON, SETTINGS_ORIG)
    if not SCRIPT_ORIG.exists() and STATUSLINE_SCRIPT.exists():
        shutil.copy2(STATUSLINE_SCRIPT, SCRIPT_ORIG)


def _wrapper_source(inner_command: str) -> str:
    """Generate the wrapper. `inner_command` is the original statusLine command
    (with ~ expanded) that we pipe the original stdin into, unchanged."""
    return f"""#!/usr/bin/env bash
# cc-usage statusline capture wrapper — REVERSIBLE; generated by cc-usage.
# Captures .rate_limits to ratelimits.json, then runs the ORIGINAL statusline with
# the same stdin and emits its stdout byte-for-byte unchanged.
# Undo with:  ccusage --restore-statusline   (or in-app: ccusage -> Settings -> Restore original)
set +e
CC_RL="$HOME/.config/cc-usage/ratelimits.json"
input=$(cat)
# Persist only when rate_limits is present, so rate-limit-less turns don't blank it.
if printf '%s' "$input" | jq -e 'has("rate_limits") and .rate_limits != null' >/dev/null 2>&1; then
  if printf '%s' "$input" | jq -c --argjson t "$(date +%s)" \\
        '{{captured_at:$t, rate_limits:.rate_limits}}' > "$CC_RL.tmp" 2>/dev/null; then
    mv -f "$CC_RL.tmp" "$CC_RL" 2>/dev/null
  else
    rm -f "$CC_RL.tmp" 2>/dev/null
  fi
fi
# Passthrough — this is the ONLY thing written to stdout, identical to the original.
printf '%s' "$input" | {inner_command}
"""


def _run_with_stdin(command: str, payload: bytes) -> bytes:
    try:
        proc = subprocess.run(
            ["bash", "-c", command], input=payload, capture_output=True, timeout=15
        )
        return proc.stdout
    except (OSError, subprocess.SubprocessError):
        return b"\x00__run_failed__"


def install() -> dict:
    """Install the wrapper reversibly. Returns a result dict (see format_result)."""
    ensure_dirs()
    if not SETTINGS_JSON.exists():
        return {"ok": False, "action": "install", "error": "no ~/.claude/settings.json found"}

    ensure_backups()
    settings = _read_settings()
    current = _current_command(settings)

    if _is_wrapped(current):
        return {
            "ok": True,
            "action": "install",
            "already": True,
            "msg": "wrapper already installed",
            "wrapper": str(WRAPPER_SCRIPT),
        }
    if not current:
        return {
            "ok": False,
            "action": "install",
            "error": "settings.json has no statusLine.command to wrap",
        }

    # Snapshot the EXACT pre-install settings bytes (restore source). Never clobber
    # an existing snapshot (it holds the true original across repeated installs).
    if not SETTINGS_PREINSTALL.exists():
        shutil.copy2(SETTINGS_JSON, SETTINGS_PREINSTALL)

    inner = current.replace("~/", "$HOME/")
    WRAPPER_SCRIPT.write_text(_wrapper_source(inner), "utf-8")
    WRAPPER_SCRIPT.chmod(0o755)

    # PROVE byte-identical output before repointing anything.
    original_out = _run_with_stdin(current, _PROOF_PAYLOAD)
    wrapper_out = _run_with_stdin(f"bash {shlex.quote(str(WRAPPER_SCRIPT))}", _PROOF_PAYLOAD)
    captured_ok = RATELIMITS_JSON.exists()
    # Drop the synthetic capture so the panel only ever shows real limits.
    try:
        RATELIMITS_JSON.unlink()
    except OSError:
        pass

    if original_out != wrapper_out:
        WRAPPER_SCRIPT.unlink(missing_ok=True)
        return {
            "ok": False,
            "action": "install",
            "error": "aborted — wrapper output differs from original; settings.json untouched",
            "identical": False,
        }

    # Repoint settings.json at the wrapper (atomic).
    settings["statusLine"] = {"type": "command", "command": f"bash {WRAPPER_SCRIPT}"}
    tmp = SETTINGS_JSON.with_suffix(".json.ccusage.tmp")
    tmp.write_text(json.dumps(settings, indent=2) + "\n", "utf-8")
    tmp.replace(SETTINGS_JSON)

    return {
        "ok": True,
        "action": "install",
        "identical": True,
        "captured_ok": captured_ok,
        "wrapper": str(WRAPPER_SCRIPT),
        "settings_preinstall": str(SETTINGS_PREINSTALL),
        "original_command": current,
    }


def restore() -> dict:
    """Undo install: revert both files to their originals and prove it by sha256."""
    ensure_dirs()

    # Prefer the exact pre-install snapshot for a byte-identical revert; otherwise
    # fall back to surgically restoring just the statusLine block from the .orig.
    method = None
    if SETTINGS_PREINSTALL.exists():
        shutil.copy2(SETTINGS_PREINSTALL, SETTINGS_JSON)
        method = "preinstall-snapshot"
    elif SETTINGS_ORIG.exists():
        try:
            orig = json.loads(SETTINGS_ORIG.read_text("utf-8"))
            cur = _read_settings()
            if isinstance(orig, dict) and "statusLine" in orig:
                cur["statusLine"] = orig["statusLine"]
            else:
                cur.pop("statusLine", None)
            tmp = SETTINGS_JSON.with_suffix(".json.ccusage.tmp")
            tmp.write_text(json.dumps(cur, indent=2) + "\n", "utf-8")
            tmp.replace(SETTINGS_JSON)
            method = "orig-statusline-block"
        except (OSError, json.JSONDecodeError, ValueError) as e:
            return {"ok": False, "action": "restore", "error": f"could not restore settings: {e}"}
    else:
        return {"ok": False, "action": "restore", "error": "no backup found to restore from"}

    WRAPPER_SCRIPT.unlink(missing_ok=True)
    # Stop showing now-stale limits once capture is disabled.
    RATELIMITS_JSON.unlink(missing_ok=True)

    # Proof (Guardrail 1): both files match their originals.
    settings_sha = _sha256(SETTINGS_JSON)
    script_sha = _sha256(STATUSLINE_SCRIPT)
    settings_target = _sha256(SETTINGS_PREINSTALL) or _sha256(SETTINGS_ORIG)
    script_target = _sha256(SCRIPT_ORIG)

    # The preinstall snapshot is only valid between an install and its restore. Drop it
    # so a later install captures a fresh snapshot of the (possibly changed) settings.
    SETTINGS_PREINSTALL.unlink(missing_ok=True)

    settings_match = settings_sha is not None and settings_sha == settings_target
    # script was never modified; matches if a backup exists to compare against
    script_match = script_target is None or script_sha == script_target

    return {
        "ok": settings_match and script_match,
        "action": "restore",
        "method": method,
        "settings_sha": settings_sha,
        "settings_target": settings_target,
        "settings_match": settings_match,
        "script_sha": script_sha,
        "script_target": script_target,
        "script_match": script_match,
    }


def status() -> dict:
    """Lightweight state for the --config menu."""
    settings = _read_settings()
    return {
        "installed": _is_wrapped(_current_command(settings)),
        "wrapper_exists": WRAPPER_SCRIPT.exists(),
        "ratelimits_exists": RATELIMITS_JSON.exists(),
    }


def format_result(result: dict) -> str:
    action = result.get("action", "?")
    if not result.get("ok"):
        return f"✗ {action} failed: {result.get('error', 'unknown error')}"

    if action == "install":
        if result.get("already"):
            return "✓ statusline wrapper already installed (no change)."
        lines = [
            "✓ statusline capture wrapper installed (reversible).",
            f"  • output proven byte-identical to the original: {result.get('identical')}",
            f"  • wrapper: {result.get('wrapper')}",
            f"  • settings.json snapshot: {result.get('settings_preinstall')}",
            "  • 5h/7d limits populate on your next Claude Code turn (usually within seconds).",
            "  • undo any time: ccusage --restore-statusline",
        ]
        return "\n".join(lines)

    # restore
    return "\n".join(
        [
            "✓ original statusline restored." if result["ok"] else "✗ restore incomplete.",
            f"  • method: {result.get('method')}",
            f"  • settings.json matches original: {result.get('settings_match')} "
            f"({(result.get('settings_sha') or '')[:12]}…)",
            f"  • statusline-command.sh matches original: {result.get('script_match')} "
            f"({(result.get('script_sha') or '')[:12]}…)",
        ]
    )
